Add retained backup setting to sql instance
nais/liberator pull request #44
Opened 2022-01-24 15:11 UTC by vebjorre

Ser APIet for retained backups ok ut?

2022-01-26 07:53 UTC, ybelMekk approved these changes
lgtm.

2022-01-26 08:09 UTC, ybelMekk requested changes

2022-01-26 08:14 UTC, ybelMekk commented on pkg/apis/nais.io/v1/naiserator_types.go
> +	// +kubebuilder:validation:Minimum=0
// +nais:doc:Link="https://cloud.google.com/sql/docs/postgres/backup-recovery/backups"

Denne kan ju også brukes hvis ønskelig.

2022-01-26 08:53 UTC, ybelMekk commented on pkg/apis/sql.cnrm.cloud.google.com/v1beta1/types.go
> +type SQLInstanceBackupRetentionSetting struct {
Må dette vare en struct? mulig de bare kan vare en int?

2022-01-26 10:30 UTC, thokra-nav commented on pkg/apis/sql.cnrm.cloud.google.com/v1beta1/types.go
> +type SQLInstanceBackupRetentionSetting struct {
Dette må følge spec-en til CRNM, så her har vi fulgt dems dokumentasjon

2022-01-26 10:36 UTC, ybelMekk commented on pkg/apis/sql.cnrm.cloud.google.com/v1beta1/types.go
> +type SQLInstanceBackupRetentionSetting struct {
My bad bro!

2022-01-26 10:38 UTC, ybelMekk commented
Kjørte du 
make generate

før du pushet? Let å glemme 😊

2022-01-26 10:38 UTC, ybelMekk approved these changes

2022-01-28 13:36 UTC, vebjorre commented
Glemte det ja.. Skal være på plass nå

2022-01-28 14:04 UTC, ybelMekk commented
Hvis du syns merge er ok , så kjør på

2022-01-28 14:44 UTC, merged